ORG 000H ;starting address
SJMP LABEL ;jumps to the LABEL

ORG 003H ; starting address for the ISR(INT0)
ACALL ISRL ; calls the ISR (interrupt service routine)
RETI ; returns from the interrupt

ORG 013H ; starting address for the ISR(INT1)
ACALL ISRR ;
RETI ;
LABEL: MOV R1,#001H ; sets the initial stage of the LEDs

MAIN: ; main function that sets the interrupt parameters in a loop
;SETB P3.2 ; sets highest priority for the interrupt INT0
SETB IT0 ; interrupt generated by a falling edge signal at INT0 (P3.2)
SETB IT1
SETB EX0 ; enables the external interrupt
SETB EX1
SETB EA ; enables the global interrupt control
MOV P2,R1
SJMP MAIN ; jumps back to the MAIN subroutine

ISRL: ; interrupt service routine
MOV A,R1
RL A
MOV R1,A
RET ; jumps to RETI

ISRR:
MOV A,R1
RR A
MOV R1,A
RET ; jumps to RETI
END
